### ISSUE TITLE
How to actually open Sponza?

### ISSUE THREAD

**Issue by dmitrykolesnikovich** [MohitSethi99/ArcEngine#18]
**Describe the bug**
I tried to add `sponza.obj` to project "Sandbox" but that does nothing. Also I tried to create empty project and add `sponza.obj` to that. Also without effect.

**To Reproduce**
1. Go to 'Arc Editor'
2. Drag and drap 'Sandbox\Assets\Models\sponza\sponza.obj' to the scene
3. See nothing

**Expected behavior**
I expect to see Sponza as you [showed](https://camo.githubusercontent.com/6744b5436519263c873775431942e0da8d2a1c044cda94269a8ca597b549d14e/68747470733a2f2f4d6f686974536574686939392e6769746875622e696f2f696d616765732f41726347616d65456e67696e652f53706f6e7a612e6a7067) in [README](https://github.com/MohitSethi99/ArcGameEngine)

**Desktop (please complete the following information):**
 - Windows SDK version: 10.0.22621.0
 - Graphics API: OpenGL

**Comment by GloriousPtr** [comment]
Did you try adding some lights to the scene and move around using wasd?
For reference, there is a scene: Sandbox/Assets/Scenes/Sponza.arc with lights and a cubemap

**Comment by GloriousPtr** [comment]
No response, closing the issue.
